#!/usr/bin/env python3
"""
Fix MICT SETA page to remove all inline popup implementations
and use only the centralized value-adds popup.
"""

import re
from pathlib import Path

def fix_mict_seta_page():
    """Clean up the MICT SETA page completely"""
    file_path = Path('setas/mict-seta.html')

    if not file_path.exists():
        print("❌ MICT SETA file not found")
        return

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Remove all banner popup CSS
    content = re.sub(
        r'/\* Sticky Banner Styles \*/.*?}',
        '/* Sticky Banner styles handled by centralized script */',
        content,
        flags=re.DOTALL
    )

    content = re.sub(
        r'\.sticky-banner \{.*?}',
        '',
        content,
        flags=re.DOTALL
    )

    content = re.sub(
        r'\.banner-popup \{.*?}',
        '',
        content,
        flags=re.DOTALL
    )

    content = re.sub(
        r'\.banner-popup\.show \{.*?}',
        '',
        content,
        flags=re.DOTALL
    )

    # Remove the entire popup HTML section
    # Find and remove everything from the popup div to where the footer starts
    content = re.sub(
        r'<!-- Banner Popup will be generated by centralized script -->.*?</footer>',
        '''    <!-- All popups and banners generated by centralized script -->

    </footer>''',
        content,
        flags=re.DOTALL
    )

    # Remove the inline JavaScript for popup functionality
    content = re.sub(
        r'// Sticky Banner Functionality.*?});',
        '// Popup functionality handled by centralized script',
        content,
        flags=re.DOTALL
    )

    # Clean up any remaining references
    content = re.sub(
        r'const stickyBanner.*?isPopupOpen = false;',
        '',
        content,
        flags=re.DOTALL
    )

    # Ensure the centralized script is included
    if 'value-adds-popup.js' not in content:
        content = content.replace(
            '<script src="https://unpkg.com/lucide@latest"></script>',
            '<script src="https://unpkg.com/lucide@latest"></script>\n    <script src="../js/value-adds-popup.js"></script>'
        )

    # Save the cleaned content
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print("✅ MICT SETA page cleaned up successfully")
    print("✅ Now uses centralized value-adds popup with SDF Service")

if __name__ == "__main__":
    fix_mict_seta_page()