#!/usr/bin/env python3
"""
Clean the end of MER SETA file to remove inline popup
"""

from pathlib import Path

def clean_mer_seta_file():
    """Remove inline popup and keep only centralized script"""
    file_path = Path('setas/mer-seta.html')

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the section just before the inline popup
    section_end = content.find('    <!-- Sticky Banner will be generated by centralized script -->')

    if section_end != -1:
        # Get everything before the popup
        clean_part = content[:section_end]

        # Add clean ending
        clean_ending = '''    <!-- Sticky Banner will be generated by centralized script -->

    <!-- Footer -->
    <footer class="bg-gray-900 text-white py-12">
        <div class="container mx-auto px-6">
            <div class="grid md:grid-cols-4 gap-8">
                <div class="md:col-span-2">
                    <div class="flex items-center mb-4">
                        <img src="../images/Logo.png" alt="SpecCon Holdings Logo" class="h-12 mr-3">
                        <div>
                            <h3 class="text-xl font-bold">SpecCon Holdings</h3>
                            <p class="text-gray-400">MER SETA Qualifications</p>
                        </div>
                    </div>
                    <p class="text-gray-400 mb-4">Empowering careers through MER SETA accredited training and qualifications.</p>
                </div>

                <div>
                    <h4 class="text-lg font-semibold mb-4">Quick Links</h4>
                    <ul class="space-y-2">
                        <li><a href="../index.html" class="text-gray-400 hover:text-white transition duration-200">Home</a></li>
                        <li><a href="../index.html#about" class="text-gray-400 hover:text-white transition duration-200">About Us</a></li>
                        <li><a href="../index.html#qualifications" class="text-gray-400 hover:text-white transition duration-200">All Qualifications</a></li>
                        <li><a href="../index.html#contact" class="text-gray-400 hover:text-white transition duration-200">Contact Us</a></li>
                    </ul>
                </div>

                <div>
                    <h4 class="text-lg font-semibold mb-4">Other SETAs</h4>
                    <ul class="space-y-2">
                        <li><a href="etdp-seta.html" class="text-gray-400 hover:text-white transition duration-200">ETDP SETA</a></li>
                        <li><a href="wr-seta.html" class="text-gray-400 hover:text-white transition duration-200">W&R SETA</a></li>
                        <li><a href="mict-seta.html" class="text-gray-400 hover:text-white transition duration-200">MICT SETA</a></li>
                        <li><a href="services-seta.html" class="text-gray-400 hover:text-white transition duration-200">Services SETA</a></li>
                    </ul>
                </div>
            </div>

            <div class="border-t border-gray-800 mt-8 pt-8 text-center">
                <p class="text-gray-400">&copy; 2025 SpecCon Holdings. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <script>
        lucide.createIcons();

        // Popup functionality handled by centralized script
    </script>
</body>
</html>'''

        # Combine clean content
        clean_content = clean_part + clean_ending

        # Save the cleaned file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(clean_content)

        print("✅ MER SETA page completely cleaned")
        print("✅ Removed all inline popup implementations")
        print("✅ Now uses only centralized script with SDF Service")
    else:
        print("❌ Could not find section marker")

if __name__ == "__main__":
    clean_mer_seta_file()